# ESSENTIALS
enable_dotfiles: true
enable_lsd: true
enable_navi: true
enable_bat: true
enable_fd: true
enable_btop: true
enable_dategrep: true
enable_glances: true
enable_lfs: true
enable_webmin: false