# roles/bind_secondary/tasks/main.yml
- name: "Role: my.named-slave - Collect service facts"
  ansible.builtin.service_facts:

- name: "Role: my.named-slave - Stop & disable systemd‑resolved if installed and running"
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  when:
    - "'systemd-resolved.service' in ansible_facts.services"
    - ansible_facts.services['systemd-resolved.service'].state   == 'running'
      or ansible_facts.services['systemd-resolved.service'].status == 'enabled'

- name: "Role: my.named-slave - Write minimal /etc/resolv.conf"
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for ns in fallback_nameservers %}
      nameserver {{ ns }}
      {% endfor %}

- name: "Role: my.named-slave - Install BIND 9 and helpers"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - bind9
      - bind9-utils
      - python3-dnspython
    state: present

- name: "Role: my.named-slave - Ensure zone directory exists and is writable by bind"
  ansible.builtin.file:
    path: "{{ bind_base_dir }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_user }}"
    mode: "0750"

# ── Configuration files (templates) ─────────────────────────────────────
- name: "Role: my.named-slave - Deploy named.conf (master include file)"
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: root
    mode: "0644"

- name: "Role: my.named-slave - Deploy named.conf.options"
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: "0644"

- name: "Role: my.named-slave - Deploy named.conf.local (slave zones)"
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: "0644"

- name: "Role: my.named-slave - Deploy named.conf.default‑zones"
  ansible.builtin.template:
    src: named.conf.default-zones.j2
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: root
    mode: "0644"

# ── Service management ──────────────────────────────────────────────────
- name: "Role: my.named-slave - Restart & enable BIND"
  ansible.builtin.service:
    name: bind9
    state: restarted
    enabled: true

# ── Post‑deployment health check ────────────────────────────────────────
- name: "Role: my.named-slave - Wait until TCP 53 answers (run from control node)"
  ansible.builtin.wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 53
    state: started
    timeout: 30
  delegate_to: localhost     # executes on controller
