- name: Restart pveproxy.service
  ansible.builtin.service:
    name: pveproxy.service
    state: restarted

- name: Reboot - watchdog changed
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible - watchdog changed
    connect_timeout: 5
    reboot_timeout: 420
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: watchdog.changed
