# Role: my.pihole
my_pihole_keepalived_setup: true
my_pihole_keepalived_instance: pihole
my_pihole_keepalived_state: BACKUP
my_pihole_keepalived_interface: eth0
my_pihole_keepalived_router_id: 1
my_pihole_keepalived_priority: 254
my_pihole_keepalived_virtual_ipv4: 192.168.1.53/24
