# add evcc repo
- name: add evcc stable repo
  template:
    src: evcc/evcc-stable.list.j2
    dest: /etc/apt/sources.list.d/evcc-stable.list
    owner: root
    group: root
    mode: 0644
  become: true

# apt-update
- import_tasks: tasks/apt-update.yml
  tags: apt-update