- name: glusterf-gstatus-json - install nginx
  apt: 
    name: nginx
    state: present
    update_cache: true
  become: true

- name: glusterf-gstatus-json - copy gstatus-status-to-json.service
  template:
    src: templates/gstatus-status-to-json.service.j2
    dest: /etc/systemd/system/gstatus-status-to-json.service
    mode: 0644

- name: glusterf-gstatus-json - copy gstatus-status-to-json.timer
  template:
    src: templates/gstatus-status-to-json.timer.j2
    dest: /etc/systemd/system/gstatus-status-to-json.timer
    mode: 0644

- name: glusterf-gstatus-json - start gstatus-status-to-json.timer
  ansible.builtin.systemd:
    state: started
    name: gstatus-status-to-json.timer