# ansible-playbook dump-variables.yml
# ansible-playbook dump-variables.yml -l <host>
---
- hosts: all
  tasks:
  - template:
      src: templates/dump_variables
      dest: /tmp/ansible_variables
  - fetch:
      src: /tmp/ansible_variables
      dest: "./tmp/{{inventory_hostname}}_ansible_variables"