# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html10.4.0. ansible-playbook apt-upgrade-all.yml -l pve_ct_vm
#
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
# --> ansible_ vars

all:

  hosts:
  
    #example.com:
  
  children:
    
    ##
    ## Proxmox: Cluster
    ##
    
    pve_cluster:
    
      hosts:

        pve01:
          ansible_host: 192.168.1.50
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve02:
          ansible_host: 192.168.1.51
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
    
    ##
    ## Proxmox: Container & VMs
    ##
    
    pve_ct_vm:

      hosts:

        pve-ct-adguard-master:
          ansible_host: 10.4.0.2
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-grafana:
          ansible_host: 10.4.0.3
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-pbs:
          ansible_host: 192.168.1.204
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-checkmk:
          ansible_host: 10.4.0.5
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-iobroker-test:
          ansible_host: 10.4.0.6
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-mariadb:
          ansible_host: 10.4.0.7
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-vpn-birkenweg-5:
          ansible_host: 10.4.0.8
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-bind-master:
          ansible_host: 10.4.0.9
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-bind-slave:
          ansible_host: 10.4.0.10
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-heimdall:
          ansible_host: 10.4.0.11
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-bitwarden:
          ansible_host: 10.4.0.12
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-adguard-slave:
          ansible_host: 10.4.0.13
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-npm:
          ansible_host: 10.4.0.14
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-vpn-hetzner:
          ansible_host: 10.4.0.15
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-tailscale:
          ansible_host: 10.4.0.17
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-vpn-hauptstrasse-6:
          ansible_host: 10.4.0.18
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-vpn-birkenweg-17:
          ansible_host: 10.4.0.19
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-iobroker:
          ansible_host: 10.4.0.20
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-ct-redis-1:
          ansible_host: 10.4.0.21
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-vm-cups:
          ansible_host: 10.4.0.31
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        pve-vm-docker:
          ansible_host: 10.4.0.33
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

    ##
    ## local Raspberry PIs
    ##
    
    rpi:

      hosts:

        freya:
          ansible_host: 192.168.1.40
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        loki:
          ansible_host: 192.168.1.41
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

    ##
    ## Wireguard VPN Gateways
    ##

    vpn_gateways:

      hosts:

        vpn-gateway-birkenweg-17:
          ansible_host: 192.168.20.2
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

        vpn-gateway-hauptstrasse-6:
          ansible_host: 192.168.30.2
          ansible_connection: ssh
          ansible_user: "{{ vault_ansible_user }}"
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

    ##
    ## Proxmox Test Environment
    ##

    pve_test:

      hosts:

        proxmox-test:
          ansible_host: 192.168.1.143
          ansible_connection: ssh
          ansible_user: root
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"