# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html10.4.0
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters

# test connecting with:
# ansible all -m ping

all:

  hosts:
  
    #example.com
  
  children:
    
    ##
    ## Proxmox: Cluster
    ##
    
    pve_cluster:
    
      hosts:

        pve01:
          ansible_host: 192.168.1.50

        #pve02:
        #  ansible_host: 192.168.1.51
    
    ##
    ## Proxmox: Container & VMs
    ##
    
    pve_ct_vm:

      hosts:

        pve-ct-adguard-master:
          ansible_host: 10.4.0.2

        pve-ct-grafana:
          ansible_host: 10.4.0.3

        pve-ct-pbs:
          ansible_host: 192.168.1.204

        #pve-ct-checkmk:
        #  ansible_host: 10.4.0.5

        pve-ct-uptimekuma:
          ansible_host: 10.4.0.6

        pve-ct-mariadb:
          ansible_host: 10.4.0.7

        pve-ct-influxdb:
          ansible_host: 10.4.0.8

        pve-ct-bind-master:
          ansible_host: 10.4.0.9

        pve-ct-bind-slave:
          ansible_host: 10.4.0.10

        pve-ct-adguard-slave:
          ansible_host: 10.4.0.13

        pve-ct-npm:
          ansible_host: 10.4.0.14

        pve-ct-vpn-hetzner:
          ansible_host: 10.4.0.15

        pve-ct-vpn-tailscale:
          ansible_host: 10.4.0.17

        pve-ct-iobroker:
          ansible_host: 10.4.0.20

        pve-ct-redis-1:
          ansible_host: 10.4.0.21

        pve-vm-cups:
          ansible_host: 10.4.0.31

        pve-vm-docker:
          ansible_host: 10.4.0.33

    ##
    ## local Raspberry PIs
    ##
    
    rpi:

      hosts:

        #freya:
        #  anwsible_host: 192.168.1.40

        loki:
          ansible_host: 192.168.1.41

    ##
    ## VPN Gateways
    ##

    vpn_gateways:

      hosts:

        vpn-gateway-birkenweg-17:
          ansible_host: 192.168.20.2

        vpn-gateway-hauptstrasse-6:
          ansible_host: 192.168.30.2

    ##
    ## Synology NAS
    ##

    nas:

      hosts:

        odin:
          ansible_host: 192.168.1.30

        ares:
          ansible_host: 192.168.1.31

    ##
    ## Proxmox Test Environment
    ##

    pve_test:

      hosts:

        #proxmox-test:
        #  ansible_host: 10.4.0.230
        #  ansible_user: root