# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html10.4.0
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters

# test connecting with:
# ansible all -m ping
# ansible <host> -m ping

all:

  children:

    ##
    ## Proxmox: Hosts
    ##

    pve_hosts:
      hosts:
        pve01:
          ansible_host: 192.168.1.50
        pve02:
          ansible_host: 192.168.1.51

    ##
    ## Proxmox: Containers
    ##

    pve_lxc:
      hosts:
        pve-ct-grafana:
          ansible_host: 10.4.0.3
        pve-ct-pihole:
          ansible_host: 192.168.1.204
        pve-ct-rustdesk:
          ansible_host: 10.4.0.5
        pve-ct-uptimekuma:
          ansible_host: 10.4.0.6
        pve-ct-mariadb:
          ansible_host: 10.4.0.7
        pve-ct-influxdb:
          ansible_host: 10.4.0.8
        pve-ct-bind-master:
          ansible_host: 10.4.0.9
        pve-ct-dev:
          ansible_host: 10.4.0.10
        pve-ct-mqtt:
          ansible_host: 10.4.0.12
        pve-ct-npm:
          ansible_host: 10.4.0.14
        pve-ct-vpn-hetzner:
          ansible_host: 10.4.0.15
        pve-ct-iobroker:
          ansible_host: 10.4.0.20
        zabbix-server:
          ansible_host: 10.4.0.195

    ##
    ## Proxmox: VMs
    ##

    pve_vm:
      hosts:
        pve-vm-docker:
          ansible_host: 10.4.0.33
        pbs-odin:
          ansible_host: 192.168.1.31
        pbs-freya:
          ansible_host: 192.168.20.4

    ##
    ## local Raspberry PIs
    ##

    rpi:
      hosts:
        loki:
          ansible_host: 192.168.1.41
        loki-new:
          ansible_host: 192.168.1.43

    ##
    ## NAS
    ##

    nas:
      hosts:
        odin:
          ansible_host: 192.168.1.30
        freya:
          ansible_host: 192.168.20.3

    ##
    ## Adblock
    ##

    adblock:
      hosts:
        loki-new: # for config check section rpi
        pve-ct-pihole: # for config check section rpi

    ##
    ## Windows
    ##

    os_windows:
      hosts:
        pve-vm-win11:
          ansible_host: 192.168.1.149
          ansible_user: ansible
          ansible_password:
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore

    ##
    ## MacOS
    ##

    os_macos:
      hosts:
        yggdrasil:
          ansible_host: 10.1.0.3
          ansible_user: darkiop

    ##
    ## Hetzner
    ##

    vpn_gw_hetzner:
      hosts:
        # connection setup defined in host_vars folder
        vpn-hetzner:
          ansible_host: 172.31.0.1

    ##
    ## VPN Gateways (external)
    ##

    vpn_gw_ext:
      hosts:
        vpn-gw-bw17:
          ansible_host: 192.168.20.2
        vpn-gw-hs6:
          ansible_host: 192.168.30.2

    ##
    ## TEST
    ##

    test:
      hosts:
        test-host-ubuntu:
          ansible_host: 10.4.0.218
          ansible_user: darkiop

        test-host-debian:
          ansible_host: 10.4.0.219
          ansible_user: darkiop
