# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html10.4.0
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters

# test connecting with:
# ansible all -m ping

all:

  hosts:
  
    #example.com
  
  children:
    
    ##
    ## Proxmox: Hosts
    ##
    
    pve_hosts:
    
      hosts:

        pve01:
          ansible_host: 192.168.1.50
          #ansible_user: root

        pve02:
          ansible_host: 192.168.1.51
          #ansible_user: root
    
    ##
    ## Proxmox: Container & VMs
    ##
    
    lxc:

      hosts:

        pve-ct-adguard-master:
          ansible_host: 10.4.0.2

        pve-ct-grafana:
          ansible_host: 10.4.0.3

        pve-ct-pbs:
          ansible_host: 192.168.1.204

        pve-ct-rustdesk:
          ansible_host: 10.4.0.5

        pve-ct-uptimekuma:
          ansible_host: 10.4.0.6

        pve-ct-mariadb:
          ansible_host: 10.4.0.7

        pve-ct-influxdb:
          ansible_host: 10.4.0.8

        pve-ct-bind-master:
          ansible_host: 10.4.0.9

        pve-ct-dev:
          ansible_host: 10.4.0.10

        #pve-ct-:
        #  ansible_host: 10.4.0.11

        pve-ct-mqtt:
          ansible_host: 10.4.0.12

        pve-ct-adguard-slave:
          ansible_host: 10.4.0.13

        pve-ct-npm:
          ansible_host: 10.4.0.14

        pve-ct-vpn-hetzner:
          ansible_host: 10.4.0.15

        #pve-ct-:
        #  ansible_host: 10.4.0.16

        #pve-ct-:
        #  ansible_host: 10.4.0.17

        #pve-ct-:
        #  ansible_host: 10.4.0.18

        #pve-ct-:
        #  ansible_host: 10.4.0.19

        pve-ct-iobroker:
          ansible_host: 10.4.0.20

        #pve-ct-redis-1:
        #  ansible_host: 10.4.0.21

    
    ##
    ## Proxmox: Container & VMs
    ##
    
    vm:

      hosts:

        #pve-vm-:
        #  ansible_host: 10.4.0.31

        pve-vm-docker:
          ansible_host: 10.4.0.33

        pbs-freya:
          ansible_host: 192.168.20.4  

    ##
    ## local Raspberry PIs
    ##
    
    rpi:

      hosts:

        loki:
          ansible_host: 192.168.1.41

    ##
    ## VPN Gateways
    ##

    vpn_gw:

      hosts:

        vpn-gw-bw17:
          ansible_host: 192.168.20.2

        vpn-gw-hs6:
          ansible_host: 192.168.30.2

    ##
    ## NAS
    ##

    nas:

      hosts:

        odin:
          ansible_host: 192.168.1.30

        freya:
          ansible_host: 192.168.20.3

    ##
    ## Proxmox Test Environment
    ##

    pve_test:

      hosts:

        pve-test:
          ansible_host: 192.168.1.60
          ansible_user: root

    ##
    ## Windows
    ##

    windows:

      hosts:

          pve-vm-win11:
          
              ansible_host: 192.168.1.149
              ansible_user: ansible
              ansible_password: ansible
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore

    ##
    ## Hetzner
    ##

    hetzner:

      hosts:

        #name:
        #  ansible_host: 
        #  anwsible_port: 
        #  ansible_ssh_private_key_file: ~/.ssh/darkiop@thor_ed25519
        #  ansible_sudo_pass: