# ansible-playbook main.yml -i hosts.yml --tags <tag1>,<tag2>
# ansible-playbook main.yml -i hosts.yml -l <host>
# ansible-playbook main.yml -i hosts.yml -e <variable>=<value>
#  -i = inventory file
#  -l = limit host
#  -e = define a variable
#
# Get a list of facts:
# ansible -m setup 
# ansible loki -m setup -a 'filter=ansible_architecture'

---
### ALL
- hosts: all

  become: true
  become_user: root

  roles: 
    
    ## ESSENTIALS (Update/Upgrade System, User, dotfiles, Tools, timezone, sudo)
    - role: my.essentials
      tags: essentials

    ## MSMTP (https://github.com/chriswayg/ansible-msmtp-mailer)
    - role: chriswayg.msmtp-mailer
      tags: msmtp

    ## NTP (https://github.com/geerlingguy/ansible-role-ntp)
    - role: geerlingguy.ntp
      tags: ntp

### PROXMOX: HOSTS
- hosts: pve_hosts

  become: true
  become_user: root

  roles:

    ## SAMBA (https://github.com/bertvv/ansible-role-samba)
    - role: bertvv.samba
      tags: samba
    
    ## PROXMOX (https://github.com/lae/ansible-role-proxmox)
    - role: lae.proxmox
      tags: proxmox
    - role: my.proxmox
      tags: proxmox

    ## SMART (https://github.com/stuvusIT/smartd)
    - role: stuvusit.smartd
      smartd_devices:
        /dev/nvme0n1:
          temperature_report_info: 55
          temperature_report_crit: 70
      tags: smartd

### PROXMOX: CT & VMs
- hosts: pve_ct_vm

  become: true
  become_user: root

  roles:

    ## SAMBA (https://github.com/bertvv/ansible-role-samba)
    - role: bertvv.samba
      tags: samba

    ## SECURITY (https://github.com/geerlingguy/ansible-role-security)
    - role: geerlingguy.security
      tags: security

### VPN-GATEWAYS
- hosts: vpn_gateways

  become: true
  become_user: root

  tasks:

    - name: Create custom.list (local dns records for pihole)
      template:
        src: pihole/custom.list.j2
        dest: "/etc/pihole/custom.list"
        owner: root
        group: root
        mode: 0644
      become: true

  roles:
    
    ## pihole (https://github.com/r-pufky/ansible_pihole)
    - role: r_pufky.pihole
      tags: pihole

  post_tasks: 

    - name: 'Update pihole gravity database'
      ansible.builtin.command: 'pihole -g'
      register: myoutput
      changed_when: myoutput.rc != 0

### pve-ct-evcc
- hosts: pve-ct-evcc

  become: true
  become_user: root

  roles:
  - role: my.evcc
    tags: evcc

### pve-ct-iobroker
- hosts: pve-ct-iobroker

  become: true
  become_user: root

  tags: iobtest

  tasks:

    - name: "create backup-scripts directory"
      become: true
      become_user: "{{ user_username }}"
      file:
        path: ~/backup-scripts
        state: directory

    - name: "copy backup-scripts"
      become: true
      become_user: "{{ user_username }}"
      copy:
        src: files/hosts/pve-ct-iobroker/
        dest: ~/backup-scripts/
        mode: 0777

    - name: "create cronjob for Backup: ioBroker"
      ansible.builtin.cron:
        name: "Backup: ioBroker"
        minute: "30"
        hour: "8"
        job: "/home/darkiop/backup-scripts/iobroker-backup-sync-iobroker.sh >/dev/null 2>&1"

    - name: "create cronjob for Backup: mariadb"
      ansible.builtin.cron:
        name: "Backup: mariadb"
        minute: "35"
        hour: "8"
        job: "/home/darkiop/backup-scripts/iobroker-backup-sync-mariadb.sh >/dev/null 2>&1"

    - name: "create cronjob for Backup: CCU"
      ansible.builtin.cron:
        name: "Backup: CCU"
        minute: "40"
        hour: "8"
        job: "/home/darkiop/backup-scripts/iobroker-backup-sync-ccu.sh >/dev/null 2>&1"

    - name: "create cronjob for Backup: Grafana"
      ansible.builtin.cron:
        name: "Backup: Grafana"
        minute: "45"
        hour: "8"
        job: "/home/darkiop/backup-scripts/iobroker-backup-sync-grafana.sh >/dev/null 2>&1"
