# ssh-copy-id -i id_rsa.pub root@host
#
# ansible-playbook run.yml -i hosts
# ansible-playbook run.yml -i hosts --tags <tag1>,<tag2>
# ansible-playbook run.yml -i hosts -l <host>
# ansible-playbook run.yml -i hosts -e <variable>=<value>
#  -i = inventory file
#  -l = limit host
#  -e = define a variable

# TODO:
# create proxmox lxc https://github.com/reminec/ansible-role-proxmox

---
### PROXMOX: CLUSTER
- hosts: pve_cluster
  become: true
  become_user: root

  roles:

    ## ESSENTIALS (Update/Upgrade System, User, dotfiles, Tools, timezone, sudo)
    - role: essentials
      tags: essentials

    ## NTP (https://github.com/geerlingguy/ansible-role-ntp)
    - role: geerlingguy.ntp
      tags: ntp

    ## SAMBA (https://github.com/bertvv/ansible-role-samba)
    - role: bertvv.samba
      tags: samba
    
    ## PROXMOX (https://github.com/lae/ansible-role-proxmox)
    # TODO: descripe
    - role: lae.proxmox
      tags: lae.proxmox
    # Install Proxmox-Dark-Theme (uninstall with: python3 /opt/xxxxxxxxxx/PVEDiscordDark.py -a uninstall)
    - role: djarbz.pvediscorddark_theme
      tags: proxmox-dark-theme
    # TODO: descripe
    - role: proxmox
      tags: proxmox
    
    ## SMART (https://github.com/stuvusIT/smartd)
    - role: stuvusit.smartd
      smartd_devices:
        /dev/nvme0n1:
          temperature_report_info: 50
          temperature_report_crit: 60
      tags: smartd
    
    ## MSMTP (https://github.com/chriswayg/ansible-msmtp-mailer)
    - role: chriswayg.msmtp-mailer
      tags: msmtp
    - role: msmtp
      tags: msmtp
  
  tasks:
  
  ## SUDO
  - import_tasks: tasks/sudoers.d.yml
    tags: sudoers

### PROXMOX: CONTAINER
- hosts: pve_ct
  become: true
  become_user: root

  roles:
    
    ## ESSENTIALS (Update/Upgrade System, User, dotfiles, Tools, timezone, sudo)
    - role: essentials
      tags: essentials
    
    ## NTP (https://github.com/geerlingguy/ansible-role-ntp)
    - role: geerlingguy.ntp
      tags: ntp
    
    ## SAMBA (https://github.com/bertvv/ansible-role-samba)
    - role: bertvv.samba
      tags: samba
    
    ## SECURITY (https://github.com/geerlingguy/ansible-role-security)
    - role: geerlingguy.security
      tags: security

    ## MSMTP (https://github.com/chriswayg/ansible-msmtp-mailer)
    - role: chriswayg.msmtp-mailer
      tags: msmtp
    - role: msmtp
      tags: msmtp

  # DEBUG
  #vars_prompt:
  #- name: "debugtest"
  #  prompt: "debugtest: "
  #  private: no
  #tasks:
  #  - import_tasks: tasks/debug.yml
  #    tags: debug