# ansible-playbook books/apt-upgrade-all.yml -i hosts.yml
# ansible-playbook books/apt-upgrade-all.yml -i hosts.yml -l lxc, vm
---
- name: Playbook apt-upgrade.yml

  hosts:
    - pve_hosts
    - pve_lxc
    - pve_vm
    - vpn_gw_ext
    - rpi

  become: true
  become_user: root

  tasks:
    - name: "Playbook: apt-upgrade.yml"
      ansible.builtin.apt:
        upgrade: safe
      register: apt
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "Playbook: apt-upgrade.yml - Output of apt-upgrade"
      ansible.builtin.debug:
        msg: "{{ apt.stdout.split('\n')[:-1] }}"

    - name: "Playbook: apt-upgrade.yml - reboot required?"
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        checksum_algorithm: md5

    - name: "Playbook: apt-upgrade.yml - reboot the box if kernel updated"
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible for kernel updates
        connect_timeout: 5
        reboot_timeout: 420
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
