# ansible-playbook apt-upgrade-all.yml
# ansible-playbook apt-upgrade-all.yml -i ../hosts.yml -l pve_ct_vm
# ansible-playbook books/apt-upgrade-all.yml -i hosts.yml -l pve_ct_vm
---
- hosts: all
  become: true
  become_user: root
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml