---
- name: Determine network configuration system
  hosts: all
  tasks:
    - name: Check if /etc/network/interfaces.d/ exists
      ansible.builtin.stat:
        path: /etc/network/interfaces.d/
      register: interfaces_d

    - name: Check if /etc/netplan/ exists
      ansible.builtin.stat:
        path: /etc/netplan/
      register: netplan

    - name: Check if NetworkManager is in use
      ansible.builtin.command: nmcli -t --fields running general
      ignore_errors: true
      register: nmcli_status
      changed_when: false

    - name: Check if /etc/sysconfig/network-scripts/ exists
      ansible.builtin.stat:
        path: /etc/sysconfig/network-scripts/
      register: ifcfg

    - name: Determine network configuration system
      ansible.builtin.set_fact:
        network_config_system: >-
          {% if interfaces_d.stat.exists %}
            interfaces.d
          {% elif netplan.stat.exists %}
            netplan
          {% elif nmcli_status.rc == 0 and 'running' in nmcli_status.stdout %}
            NetworkManager
          {% elif ifcfg.stat.exists %}
            ifcfg
          {% else %}
            unknown
          {% endif %}

    - name: Print the network configuration system
      ansible.builtin.debug:
        msg: "The network configuration system in use is: {{ network_config_system }}"

- name: Configure network settings for Debian and Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Setup static IP address configuration for Debian (/etc/network/interfaces)
      ansible.builtin.template:
        src: network-config.j2
        dest: /etc/network/interfaces.d/network-config
        owner: root
        group: root
        mode: "0644"
      tags: setup-static-ip-address
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['distribution_version'] == "12"
        - my_essentials_network_mode == 'static'
      notify: Restart networking.service

    - name: Create netplan configuration file for Ubuntu
      ansible.builtin.copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            ethernets:
              {{ my_essentials_network_interface_name }}:
                dhcp4: no
                addresses:
                  - {{ my_essentials_network_static_ip_1 }}/24
                routes:
                  - to: default
                    via: {{ my_essentials_network_gateway }}
                nameservers:
                  addresses:
                    - {{ my_essentials_network_dns_1 }}
        mode: "0755"
      tags: setup-static-ip-address
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - my_essentials_network_mode == 'static'

    - name: Apply netplan configuration
      ansible.builtin.command: netplan apply
      register: result
      changed_when: false
      tags: setup-static-ip-address
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - my_essentials_network_mode == 'static'

    - name: Debug netplan apply result
      ansible.builtin.debug:
        var: result
      tags: setup-static-ip-address
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - my_essentials_network_mode == 'static'

  handlers:
    - name: Restart networking.service
      ansible.builtin.service:
        name: networking
        state: restarted
