# ansible-playbook books/cleanup-debian-based-os.yml -i hosts.yml
---
- name: "Playbook: cleanup-debian-based-os.yml"

  hosts:
    - pve_hosts
    - pve_lxc
    - pve_vm
    - vpn_gw_ext

  become: true
  become_user: root

  tasks:
    - name: Register journalctl installation status
      ansible.builtin.command: which journalctl
      changed_when: false
      failed_when: false
      register: journalctl_installed

    - name: Run journalctl log cleanup
      become: true
      become_user: root
      ansible.builtin.command: journalctl --vacuum-time=2d
      changed_when: false
      when: journalctl_installed

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true
