# https://stackoverflow.com/questions/18839509/where-can-i-get-a-list-of-ansible-pre-defined-variables
#
# ansible-playbook dump-variables.yml
# ansible-playbook dump-variables.yml -l <host>
#
---
- name: "Playbook: dump-variables.yml"

  hosts: all

  tasks:
    - name: Template
      ansible.builtin.template:
        src: ./dump_variables.j2
        dest: /tmp/dump_variables
        mode: "0755"

    - name: Fetch
      ansible.builtin.fetch:
        src: /tmp/ansible_variables
        dest: "../tmp/ansible_variables/{{inventory_hostname}}"
