# ansible-playbook books/facts.yml -i hosts.yml
# ansible-playbook books/facts.yml -i hosts.yml -l lxc, vm
---
- hosts: all

  become: true
  become_user: root

  tasks:

    - name: Show facts available on the system
      debug:
        var: ansible_facts