# ansible-playbook books/facts.yml -i hosts.yml
# ansible-playbook books/facts.yml -i hosts.yml -l lxc, vm
---
- name: "Playbook: facts.yml"

  hosts: all

  become: true
  become_user: root

  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts
