---
- name: Install Node.js, npm and @openai/codex
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and install nodejs & npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Install @openai/codex globally via npm
      npm:
        name: "@openai/codex"
        global: yes
        state: present
