---
- name: "Playbook: pi-detect.yml"

  hosts: all

  gather_facts: true

  tasks:
    - name: Say Yes
      debug:
        msg: I am a pi
      when:
        - ansible_facts['architecture'] == "aarch64"
        - ansible_facts['kernel'].find('rpi') != -1
