# ansible-playbook pve-migrate-all-nodes -l pve01
# Example:
#  search: group pve01
#  replace: group pve02
# TODO Fix: if /etc/pve/ha/resources.cfg.bak does not exist > auth error before copying
---
- hosts: pve_hosts
  become: true
  become_user: root

  vars_prompt:

  - name: "search"
    prompt: "search (e.g. 'group pve01')"
    private: no

  - name: "replace"
    prompt: "replace (e.g. 'group pve02')"
    private: no

  tasks:

    - name: Backup resources.cfg
      become: true
      become_user: root
      copy:
        src: /etc/pve/ha/resources.cfg
        dest: /etc/pve/ha/resources.cfg.bak
        remote_src: yes

    - name: Edit resources.cfg
      replace:
        path: /etc/pve/ha/resources.cfg
        regexp: "{{ search }}"
        replace: "{{ replace }}"