# ansible-playbook books/reboot.yml -i hosts.yml -l lxc, vm
---
- name: "Playbook: reboot.yml"

  hosts:
    - pve_hosts
    - pve_lxc
    - pve_vm
    - vpn_gw_ext

  become: true
  become_user: root

  tasks:
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
