# ansible-playbook books/reboot.yml -i hosts.yml -l lxc, vm
---
- name: "Playbook: reboot.yml"

  hosts: all

  become: true
  become_user: root

  tasks:

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
