- name: Show PRETTY_NAME from /etc/os-release on all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Read /etc/os-release
      ansible.builtin.slurp:
        src: /etc/os-release
      register: os_release_raw

    - name: Extract PRETTY_NAME line
      ansible.builtin.set_fact:
        pretty_name_line: "{{ os_release_raw['content'] | b64decode | regex_search('^PRETTY_NAME=\"(.*)\"$', '\\1', multiline=True) }}"

    - name: Show PRETTY_NAME
      ansible.builtin.debug:
        msg: "{{ pretty_name_line }}"

    - name: Write PRETTY_NAME to local file
      delegate_to: localhost
      ansible.builtin.copy:
        content: |
          {% for host in ansible_play_hosts %}
          {{ host }}: {{ hostvars[host]['pretty_name_line'] | join('') }}
          {% endfor %}
        dest: ./show-os-release-results.txt
        mode: "0644"
