# ansible-playbook update-dotfiles.yml
# ansible-playbook update-dotfiles.yml -l <host>
---
- name: "Playbook: update-dotfiles.yml"
  hosts:
    - pve_hosts
    - pve_lxc
    - pve_vm
    - vpn_gw_ext
  become: true
  become_user: root

  tasks:
    # my_essentials_user_username
    - name: "Playbook: dotfiles - clone the latest dotfiles repo to {{ my_essentials_user_username }}/dotfiles"
      become: true
      become_user: "{{ my_essentials_user_username }}"
      ansible.builtin.git:
        repo: "{{ my_essentials_user_dotfiles_repo }}"
        dest: /home/{{ item }}/dotfiles
        recursive: true
        force: true
        update: true
        version: master
      with_items: "{{ my_essentials_user_username }}"

    # root
    - name: "Playbook: dotfiles - clone the latest dotfiles repo to /root/dotfiles"
      ansible.builtin.git:
        repo: "{{ my_essentials_user_dotfiles_repo }}"
        dest: /root/dotfiles
        recursive: true
        force: true
        update: true
        version: master
