# ansible-playbook update-dotfiles.yml
# ansible-playbook update-dotfiles.yml -l <host>
---
- hosts: all
  become: true
  become_user: root
  tasks:
    - import_tasks: ../tasks/dotfiles-update.yml
      tags: dotfiles-update