# Test Ansible with Windows

- name: "Playbook: win.yml"
  hosts: pve-vm-win11

  tasks:

    - name: Install all critical and security updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: installed
      register: update_result

    - name: Reboot host if required
      ansible.windows.win_reboot:
      when: update_result.reboot_required

    - name: Install chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name:
          - chocolatey
          - chocolatey-core.extension
        state: present

    - name: Install multiple packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - procexp
          - firefox
          - windirstat
          - geekuninstaller
        state: present

    - name: Update
      chocolatey.chocolatey.win_chocolatey:
        name: all
        state: latest
        ignore_checksums: true
