- name: Collect service facts
  ansible.builtin.service_facts:

# ── Installation ─────────────────────────────────────────────────────────────────────────────────
- name: Include disable-systemd-resolved.yml tasks
  ansible.builtin.include_tasks: disable-systemd-resolved.yml

- name: Include install.yml tasks
  ansible.builtin.include_tasks: install.yml

# ── Configuration files (templates) ──────────────────────────────────────────────────────────────
- name: Include forward zonefile tasks when enabled
  ansible.builtin.include_tasks: zonefiles-forward.yml
  when: my_named_mode == 'master'

# the zonefiles-reverse.yml includes also the definition of the variable my_named_reverse_zone_definitions
# which is used in named.conf.j2
- name: Include reverse zonefile tasks when enabled
  ansible.builtin.include_tasks: zonefiles-reverse.yml

- name: Include named.conf creation tasks
  ansible.builtin.include_tasks: named.conf.yml

# ── Post-deployment health check ─────────────────────────────────────────────────────────────────
- name: Reboot all hosts
  ansible.builtin.reboot:

- name: Wait until TCP 53 answers
  ansible.builtin.wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 53
    state: started
    timeout: 60
  delegate_to: localhost
