- name: Ensure zone directory exists
  ansible.builtin.file:
    path: "{{ my_named_zone_dir }}"
    state: directory
    owner: bind
    group: bind
    mode: "0755"

- name: Render forward zone files
  ansible.builtin.template:
    src: zones/forward.j2
    dest: "{{ my_named_zone_dir }}/{{ item.file }}"
    owner: bind
    group: bind
    mode: "0640"
  loop: "{{ my_named_zone_definitions }}"
  notify: Reload bind

- name: Validate forward zones with named‑checkzone
  ansible.builtin.command: >
    named-checkzone {{ item.name }} {{ my_named_zone_dir }}/{{ item.file }}
  loop: "{{ my_named_zone_definitions }}"
  register: zonecheck
  changed_when: false
