- name: Render forward zone files
  ansible.builtin.template:
    src: zones/forward.j2
    dest: "{{ my_named_zone_dir }}/{{ item.file }}"
    owner: "{{ my_named_bind_user }}"
    group: "{{ my_named_bind_user }}"
    mode: "0640"
  loop: "{{ my_named_zone_definitions }}"

- name: Validate forward zones with named‑checkzone
  ansible.builtin.command: >
    named-checkzone {{ item.name }} {{ my_named_zone_dir }}/{{ item.file }}
  loop: "{{ my_named_zone_definitions }}"
  register: zonecheck
  changed_when: false
