#- name: set the name of a sudo group
#  set_fact:
#    sudo_group: sudo
  
- name: create login user "{{ username }}"
  become: yes
  user:
    name: "{{ item }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: 
      - sudo
      - users
    state: present
    append: true
    update_password: on_create
  with_items: "{{ username }}"

- name: ensure group "{{ username }}" exists
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ username }}"

#- name: allow 'sudo' group to have passwordless sudo
#  become: yes
#  lineinfile:
#    path: /etc/sudoers
#    state: present
#    regexp: '^%{{ sudo_group }}'
#    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
#    validate: '/usr/sbin/visudo -cf %s'

- name: set the default shell
  user: 
    name: "{{ item }}"
    shell: "{{ shell }}"
  with_items: "{{ username }}"

- name: add SSH public key
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/ssh/'+ item + '.key.pub') }}"
  with_items: "{{ username }}"

- name: ensure group "sambashare" exists
  when: enable_samba | default(False) 
  become: yes
  group:
    name: "sambashare"
    state: present

- name: append the samba group
  when: enable_samba | default(False) 
  become: yes
  user:
    name: "{{ username }}"
    groups: 
      - sambashare
    append: true