---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe
  register: apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- debug: msg={{ apt.stdout.split('\n')[:-1] }}

- name: Install gpg
  become: true
  become_user: root
  apt: 
    name: "gpg"
    state: present

- name: Add Webmin key
  apt_key:
    url: 'http://www.webmin.com/jcameron-key.asc'
    state: present

- name: Add Webmin repositories
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb http://download.webmin.com/download/repository sarge contrib'
    - 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

- name: Install Webmin
  become: true
  become_user: root
  apt: 
    name: "webmin"
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'