# -------------------------------------------------------------
# install: cheat.sh
# https://github.com/chubin/cheat.sh#installation
# https://github.com/chubin/cheat.sh#command-line-client-chtsh
# config: ~/.cht.sh/cht.sh.conf
# -------------------------------------------------------------

#chmod +x /usr/local/bin/cht.sh
#mkdir -p $HOME/.cht.sh
#ln -s files/config/cht.sh/cht.sh.conf $HOME/.cht.sh/cht.sh.conf

- name: cht.sh - Download cht.sh
  get_url:
    url: https://cht.sh/:cht.sh
    dest: /usr/local/bin/cht.sh

- name: cht.sh - Change file ownership, group and permissions
  file:
    path: /usr/local/bin/cht.sh
    owner: root
    group: root
    mode: '0755'

- name: cht.sh - create .config directory for "{{ user_username }}"
  become: true
  become_user: "{{ user_username }}"
  file:
    path: $HOME/.cht.sh
    state: directory
    mode: '0755'

- name: cht.sh - copy config.yaml to ~/.cht.sh - "{{ user_username }}"
  become: true
  become_user: "{{ user_username }}"
  copy: 
    src: files/config/cht.sh/cht.sh.conf
    dest: ~/.cht.sh/cht.sh.conf
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
    mode: "0644"

- name: cht.sh - create .config directory for root
  become: true
  become_user: root
  file:
    path: /root/.cht.sh
    state: directory
    mode: '0755'

- name: cht.sh - copy config.yaml to ~/.cht.sh - root
  become: true
  become_user: root
  copy: 
    src: files/config/cht.sh/cht.sh.conf
    dest: ~/.cht.sh/cht.sh.conf
    owner: root
    group: root
    mode: "0644"