- name: lsd - install github3 module
  pip:
    name: lsd - github3.py

- name: lsd - get the latest release version
  github_release:
    user: Peltoche
    repo: lsd
    action: latest_release
  register: release

- name: lsd - show version
  debug:
    var: release

- name: lsd - get the latest amd64 deb package
  get_url: 
    url: "https://github.com/Peltoche/lsd/releases/download/{{ release['tag'] }}/lsd_{{ release['tag'] }}_amd64.deb"
    dest: /tmp

- name: lsd - install the deb package 
  shell:
    cmd: dpkg -i /tmp/lsd_{{ release['tag'] }}_amd64.deb && rm /tmp/lsd_{{ release['tag'] }}_amd64.deb

- name: lsd - create .config directory for "{{ username }}"
  become: true
  become_user: "{{ username }}"
  shell:
    cmd: mkdir -p ~/.config/lsd

- name: lsd - copy config.yaml to .config directory
  become: true
  become_user: "{{ username }}"
  copy: 
    src: files/config/lsd/config.yaml
    dest: ~/.config/lsd/config.yaml
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: lsd - create .config directory for root
  become: true
  become_user: root
  shell:
    cmd: mkdir -p /root/.config/lsd

- name: lsd - copy config.yaml to .config directory
  become: true
  become_user: root
  copy: 
    src: files/config/lsd/config.yaml
    dest: /root/.config/lsd/config.yaml
    owner: root
    group: root
    mode: "0644"