- name: install github3 module
  pip:
    name: github3.py

- name: get the latest release version
  github_release:
    user: aristocratos
    repo: btop
    action: latest_release
  register: release

- name: show version
  debug:
    var: release

- name: mkdir temp directory
  shell:
    cmd: mkdir -p /tmp/btop

- name: download & unarchive the latest version
  ansible.builtin.unarchive:
    src: https://github.com/aristocratos/btop/releases/download/{{ release['tag'] }}/btop-x86_64-linux-musl.tbz
    dest: /tmp/btop
    remote_src: yes
  when: '"x86_64" in ansible_architecture'

- name: run install.sh
  remote_user: "root"
  command: chdir=/tmp/btop /bin/bash /tmp/btop/install.sh

- name: remove temp directory
  shell:
    cmd: rm -r /tmp/btop