- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe
  register: apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- debug: msg={{ apt.stdout.split('\n')[:-1] }}

- name: Install python3-pip
  become: true
  become_user: root
  apt: 
    name: "python3-pip"
    state: present

- name: Delete EXTERNALLY-MANAGED
  ansible.builtin.file:
    state: absent
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED

- name: navi - install github3 module
  pip:
    name: github3.py

- name: navi - install fzf
  become: true
  become_user: root
  apt: 
    name: fzf
    state: present
    update_cache: true

- name: navi - get the latest release version
  github_release:
    user: denisidoro
    repo: navi
    action: latest_release
  register: release

- name: navi - show version
  debug:
    var: release

- name: navi - download & unarchive the latest version
  unarchive:
    src: https://github.com/denisidoro/navi/releases/download/{{ release['tag'] }}/navi-{{ release['tag'] }}-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: navi - Change file ownership, group and permissions
  file:
    path: /usr/local/bin/navi
    owner: root
    group: root
    mode: '0755'