# https://github.com/Canop/lfs

# x86_64
- name: lfs - download latest release as zip file
  get_url: 
    url: https://dystroy.org/lfs/download/x86_64-linux/lfs
    dest: /usr/local/bin
    mode: 0755
  when: ansible_architecture == "x86_64"

# armv7
- name: lfs - download latest release as zip file
  get_url: 
    url: https://dystroy.org/lfs/download/armv7-unknown-linux-gnueabihf/lfs
    dest: /usr/local/bin
    mode: 0755
  when: ansible_architecture == "armv7l"