- name: btop - install github3 module
  pip:
    name: github3.py

- name: btop - get the latest release version
  github_release:
    user: aristocratos
    repo: btop
    action: latest_release
  register: release

- name: btop - show version
  debug:
    var: release

- name: btop - mkdir temp directory
  shell:
    cmd: mkdir -p /tmp/btop

- name: btop - download & unarchive the latest version
  unarchive:
    src: https://github.com/aristocratos/btop/releases/download/{{ release['tag'] }}/btop-x86_64-linux-musl.tbz
    dest: /tmp/btop
    remote_src: yes
  when: '"x86_64" in ansible_architecture'

- name: btop - run install.sh
  remote_user: "root"
  command: chdir=/tmp/btop /bin/bash /tmp/btop/install.sh

- name: btop - Change file ownership, group and permissions
  file:
    path: /usr/local/bin/btop
    owner: root
    group: root
    mode: '0755'

- name: btop - remove temp directory
  shell:
    cmd: rm -r /tmp/btop