# https://github.com/sharkdp/fd

- name: fd - install github3 module
  pip:
    name: github3.py

- name: fd - get the latest release version
  github_release:
    user: sharkdp
    repo: fd
    action: latest_release
  register: release

- name: fd - show version
  debug:
    var: release

- name: fd - get the latest amd64 deb package
  get_url: 
    url: "https://github.com/sharkdp/fd/releases/download/{{ release['tag'] }}/fd_{{ release['tag'] | regex_replace('^v','') }}_amd64.deb"
    dest: /tmp
  when: '"x86_64" in ansible_architecture'

- name: fd - install the deb package 
  shell:
    cmd: dpkg -i /tmp/fd_{{ release['tag'] | regex_replace('^v','') }}_amd64.deb && rm /tmp/fd_{{ release['tag'] | regex_replace('^v','') }}_amd64.deb