- name: Create a sudoers file for {{ user_username }} 
  template:
    src: sudoers.d.j2
    dest: /etc/sudoers.d/{{ user_username }}
    owner: root
    group: root
    mode: ug+rwX,o=
    force: yes

- name: check if host specifig sudoers.d file exists
  become: false
  local_action: stat path=files/sudoers.d/{{ inventory_hostname }}
  register: file

- name: copy host specifig sudoers.d file
  become: true
  become_user: root
  copy:
    src: files/sudoers.d/{{ inventory_hostname }}
    dest: /etc/sudoers.d/{{ inventory_hostname }}
    mode: 0644
  when: file.stat.exists