# Role: bertvv.samba
samba_shares:
  - name: lets-encrypt-ro
    guest_ok: yes
    public: yes
    read_only: yes
    writable: no
    browseable: yes
    owner: root
    path: /etc/letsencrypt/archive/birkenweg.walk-steinweiler.de
    valid_users: "{{ my_essentials_user_username }}"
    write_list: "{{ my_essentials_user_username }}"
    group: root
    user: root
