# SAMBA
samba_shares:
  - name: etc-bind
    guest_ok: no
    public: yes
    read_only: no
    writable: yes
    browseable: yes
    owner: "{{ user_username }}"
    path: "/etc/bind"
    valid_users: "{{ user_username }}"
    write_list: "{{ user_username }}"
    group: root
    user: root
  
  - name: var-cache-bind
    guest_ok: no
    public: yes
    read_only: no
    writable: yes
    browseable: yes
    owner: "{{ user_username }}"
    path: "/var/cache/bind"
    valid_users: "{{ user_username }}"
    write_list: "{{ user_username }}"
    group: bind
    user: bind