# Role: bertvv.samba
samba_shares:
  - name: etc-bind
    guest_ok: false
    public: true
    read_only: true
    writable: true
    browseable: true
    owner: "{{ my_essentials_user_username }}"
    path: /etc/bind
    valid_users: "{{ my_essentials_user_username }}"
    write_list: "{{ my_essentials_user_username }}"
    group: root
    user: root

  - name: var-cache-bind
    guest_ok: false
    public: true
    read_only: false
    writable: true
    browseable: true
    owner: "{{ my_essentials_user_username }}"
    path: /var/cache/bind
    valid_users: "{{ my_essentials_user_username }}"
    write_list: "{{ my_essentials_user_username }}"
    group: bind
    user: bind
