- name: "Role: my.mqtt - install mosquitto & mosquitto-clients"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mosquitto
    - mosquitto-clients

- name: "Role: my.mqtt - delete existing /etc/mosquitto/passwd"
  become: true
  ansible.builtin.file:
    path: /etc/mosquitto/passwd
    state: absent

- name: "Role: my.mqtt - create /etc/mosquitto/passwd"
  become: true
  ansible.builtin.file:
    path: /etc/mosquitto/passwd
    mode: "0644"
    state: touch

- name: "Role: my.mqtt - run mosquitto_passwd command and capture the output"
  become: true
  ansible.builtin.command: mosquitto_passwd -b /etc/mosquitto/passwd "{{ my_mqtt_username }}" "{{ my_mqtt_password }}"
  register: passwd_output
  changed_when: false

- name: "Role: my.mqtt - create custom config file for mosquitto"
  ansible.builtin.copy:
    dest: /etc/mosquitto/conf.d/custom.conf
    owner: root
    group: root
    mode: "0664"
    content: |
      listener 1883
      allow_anonymous false
      password_file /etc/mosquitto/passwd
  notify: Restart mosquitto
