- name: my.mqtt - install mosquitto & mosquitto-clients
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mosquitto
    - mosquitto-clients

- name: my.mqtt - delete existing /etc/mosquitto/passwd
  become: true
  file:
    path: /etc/mosquitto/passwd
    state: absent

- name: my.mqtt - create /etc/mosquitto/passwd
  become: true
  file:
    path: /etc/mosquitto/passwd
    mode: 0644
    state: touch

- name: my.mqtt - run mosquitto_passwd command and capture the output
  become: true
  shell: mosquitto_passwd -b /etc/mosquitto/passwd "{{ my_mqtt_username }}" "{{ my_mqtt_password }}"
  register: passwd_output
  changed_when: false

#- name: my.mqtt - read the content of /etc/mosquitto/passwd
#  become: true
#  shell: cat /etc/mosquitto/passwd
#  register: passwd_content

#- name: my.mqtt - display the content of /etc/mosquitto/passwd
#  debug:
#    msg: "Content of /etc/mosquitto/passwd:\n{{ passwd_content.stdout }}"

- name: my.mqtt - create custom config file for mosquitto
  copy:
    dest: /etc/mosquitto/conf.d/custom.conf
    owner: root
    group: root
    mode: 0664
    content: |
      listener 1883
      allow_anonymous false
      password_file /etc/mosquitto/passwd
  notify: Restart mosquitto

#- name: my.mqtt - read the content of /etc/mosquitto/conf.d/custom.conf
#  become: true
#  shell: cat /etc/mosquitto/conf.d/custom.conf
#  register: custom_conf_content

#- name: my.mqtt - display the content of /etc/mosquitto/passwd
#  debug:
#    msg: "Content of /etc/mosquitto/conf.d/custom.conf:\n{{ custom_conf_content.stdout }}"