---
- name: "Role my.gitea: install"
  ansible.builtin.include_tasks: install.yml
  tags:
    - role-my.gitea
    - install

- name: "Role my.gitea: configure"
  ansible.builtin.include_tasks: configure.yml
  tags:
    - role-my.gitea
    - configure

- name: "Role my.gitea: service"
  ansible.builtin.include_tasks: service.yml
  tags:
    - role-my.gitea
    - service
