# Linux
- name: "Role: my.ssh - Place authorized SSH keys for each user"
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: ~/.ssh/authorized_keys
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0600"
  when:
    - ansible_facts['os_family'] != 'Darwin' # Not MacOS
  with_items: "{{ users }}"

# MacOS
# TODO /Users -> ~
- name: "Role: my.ssh - Place authorized SSH keys for {{ ansible_user }}"
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: /Users/{{ ansible_user }}/.ssh/authorized_keys
    owner: "{{ ansible_user }}"
    group: staff
    mode: "0600"
  when: ansible_facts['os_family'] == 'Darwin'
