# TODO add private keys

- name: my.ssh - create SSH directory
  file:
    state: directory
    name: .ssh
    mode: '0700'

- import_tasks: user-config.yml
  tags: user-config

- import_tasks: authorized-keys.yml
  tags: authorized-keys