- name: "Role: my.ssh - set fact for users user-config"
  ansible.builtin.set_fact:
    users:
      - root
      - "{{ my_essentials_user_username }}"

- name: "Role: my.ssh - create SSH directory for {{ my_essentials_user_username }}"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.file:
    state: directory
    path: "/home/{{ my_essentials_user_username }}/.ssh"
    mode: "0700"

- name: "Role: my.ssh - import user-config.yml"
  ansible.builtin.import_tasks: user-config.yml
  tags: ssh-user-config

- name: "Role: my.ssh - import authorized-keys.yml"
  ansible.builtin.import_tasks: authorized-keys.yml
  tags: ssh-authorized-keys
# TODO add private keys
# - import_tasks: private-keys.yml
#  tags: private-keys
