- name: "Role: my.ssh - Create SSH config for each user"
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: config.j2
    dest: ~/.ssh/config
    mode: "0700"
  with_items: "{{ users }}"
