# Network Configuration
my_essentials_network_mode: static # static, dhcp - default/empty = dhcp
my_essentials_network_interface_name: eth0
my_essentials_network_static_ip_1: "{{ vault_my_essentials_network_static_ip_1 }}"
my_essentials_network_static_ip_2: "{{ vault_my_essentials_network_static_ip_2 }}"
my_essentials_network_gateway: "{{ vault_my_essentials_network_gateway }}"
my_essentials_network_domain_name: "{{ vault_my_essentials_network_domain_name }}"
my_essentials_network_domain_search: "{{ vault_my_essentials_network_domain_search }}"
my_essentials_network_dns_1: "{{ vault_my_essentials_network_dns_1 }}"
my_essentials_network_dns_2: "{{ vault_my_essentials_network_dns_2 }}"

# Role: my.essentials - apt install aditional_software task
my_essentials_apt_aditional_packages:
  - ser2net

# Role: geerlingguy.security
# allow root login for ssh -> qdevice pve
security_ssh_permit_root_login: "yes"
security_ssh_password_authentication: "yes"
security_ssh_allowed_users:
  - "{{ my_essentials_user_username }}"
  - root
