# Role: bertvv.samba
samba_shares:
  - name: opt-heimdall
    guest_ok: no
    public: yes
    read_only: no
    writable: yes
    browseable: yes
    owner: "{{ user_username }}"
    path: "/opt/heimdall"
    valid_users: "{{ user_username }}"
    write_list: "{{ user_username }}"
    group: www-data
    user: www-data