---
- name: "Role: my.docker - install Docker CE"
  ansible.builtin.include_role:
    # https://github.com/geerlingguy/ansible-role-docker)
    name: geerlingguy.docker

- name: "Role: my.docker - create docker main directory"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.file:
    path: /home/{{ my_essentials_user_username }}/docker
    state: directory
    mode: "0755"

- name: "Role: my.docker - create docker prod directory"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.file:
    path: /home/{{ my_essentials_user_username }}/docker/prod
    state: directory
    mode: "0755"

- name: "Role: my.docker - create docker test directory"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.file:
    path: /home/{{ my_essentials_user_username }}/docker/test
    state: directory
    mode: "0755"
