- name: my.docker - install Docker CE
  include_role:
    # https://github.com/geerlingguy/ansible-role-docker)
    name: geerlingguy.docker

- name: my.docker - create docker main directory
  become: true
  become_user: "{{ my_essentials_user_username }}"
  file:
    path: /home/{{ my_essentials_user_username }}/docker
    state: directory

- name: my.docker - create docker prod directory
  become: true
  become_user: "{{ my_essentials_user_username }}"
  file:
    path: /home/{{ my_essentials_user_username }}/docker/prod
    state: directory

- name: my.docker - create docker test directory
  become: true
  become_user: "{{ my_essentials_user_username }}"
  file:
    path: /home/{{ my_essentials_user_username }}/docker/test
    state: directory