# https://wiki.archlinux.org/title/Keepalived
# https://docs.linuxfabrik.ch/software/keepalived.html
# https://www.reddit.com/r/pihole/comments/d5056q/tutorial_v2_how_to_run_2_pihole_servers_in_ha/?rdt=34610
# https://www.keepalived.org/manpage.html
# https://www.linux-magazin.de/ausgaben/2015/07/einfuehrung2/

- name: "Role: my.keepalived - enable nonlocal IP binding"
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_nonlocal_bind = 1
      net.ipv6.ip_nonlocal_bind = 1
  notify: Reload sysctl config

- name: "Role: my.keepalived - force install keepalived package"
  ansible.builtin.apt:
    force_apt_get: true
    name: keepalived

- name: "Role: my.keepalived - configure keepalived"
  ansible.builtin.template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.j2
    mode: "0644"
  notify: Restart keepalived
# TODO check pihole-ftl status with script
# global_defs {
# notification_email {
#        {{ my_essentials_user_email }}
#    }
#    notification_email_from {{ my_essentials_user_email }}
#    smtp_server localhost
#    smtp_connect_timeout 30
# }
#
# vrrp_instance VI_1 {
#     state MASTER
#     interface eth0
#     virtual_router_id 51
#     priority 100
#     advert_int 1
#     authentication {
#         auth_type PASS
#         auth_pass PASSWORD
#     }
#     virtual_ipaddress {
#         10.0.0.100
#     }
# }
