---
# watchdog config
- name: watchdog-config - setup
  copy:
    content: "WATCHDOG_MODULE={{ pve_watchdog }}"
    dest: /etc/default/pve-ha-manager
    mode: 0640
  register: watchdog

- name: watchdog-config - reboot
  reboot:
    msg: "Reboot initiated by Ansible - watchdog changed"
    connect_timeout: 5
    reboot_timeout: 420
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: watchdog.changed