# sudo
sudoers_bin_nopasswd: /usr/bin/apt-get, /usr/bin/apt, /usr/sbin/reboot, /usr/sbin/poweroff, /usr/bin/systemctl

# SAMBA
samba_shares:
  - name: opt-iobroker
    guest_ok: no
    public: yes
    read_only: no
    writable: yes
    browseable: yes
    owner: "{{ user_username }}"
    path: "/opt/iobroker"
    valid_users: "{{ user_username }}"
    write_list: "{{ user_username }}"
    group: iobroker
    user: iobroker