- name: my.essentials - adduser.yml - create login user "{{ user_username }}"
  become: true
  user:
    name: "{{ item }}"
    password: "{{ user_password | password_hash('sha512') }}"
    groups: 
      - sudo
      - users
    state: present
    append: true
    update_password: on_create
  with_items: "{{ user_username }}"

- name: my.essentials - adduser.yml - ensure group "{{ user_username }}" exists
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_username }}"

- name: my.essentials - adduser.yml - set the default shell
  user: 
    name: "{{ item }}"
    shell: "{{ user_shell }}"
  with_items: "{{ user_username }}"

- name: my.essentials - adduser.yml - ensure group "sambashare" exists
  when: enable_samba | default(False) 
  become: true
  group:
    name: "sambashare"
    state: present

- name: my.essentials - adduser.yml - append the samba group
  when: enable_samba | default(False) 
  become: true
  user:
    name: "{{ user_username }}"
    groups: 
      - sambashare
    append: true