- name: "Role: my.essentials - adduser.yml - create login user '{{ my_essentials_user_username }}'"
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ my_essentials_user_password | password_hash('sha512') }}"
    groups:
      - sudo
      - users
    state: present
    append: true
    update_password: on_create
  with_items: "{{ my_essentials_user_username }}"

- name: "Role: my.essentials - adduser.yml - ensure group '{{ my_essentials_user_username }}' exists"
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ my_essentials_user_username }}"

- name: "Role: my.essentials - adduser.yml - set the default shell"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ my_essentials_user_shell }}"
  with_items: "{{ my_essentials_user_username }}"

- name: "Role: my.essentials - adduser.yml - ensure group sambashare exists"
  when: enable_samba | default(false)
  become: true
  ansible.builtin.group:
    name: sambashare
    state: present

- name: "Role: my.essentials - adduser.yml - append the samba group"
  when: enable_samba | default(false)
  become: true
  ansible.builtin.user:
    name: "{{ my_essentials_user_username }}"
    groups:
      - sambashare
    append: true
