- name: my.essentials - apt-upgrade.yml - apt-upgrade
  apt:
    upgrade: safe
  register: apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- debug: msg={{ apt.stdout.split('\n')[:-1] }}

- name: my.essentials - apt-upgrade.yml - check if a reboot is needed on all servers
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    checksum_algorithm: md5

- name: my.essentials - apt-upgrade.yml - reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 420
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists