- name: my.essentials - check-and-install-git.yml - force install of git
  apt: 
    name: git
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'