# https://github.com/amix/vimrc

- name: "Role: my.essentials - install-vimrc.yml - ensure git is installed"
  ansible.builtin.apt:
    name: git
    state: present

- name: "Role: my.essentials - install-vimrc.yml - define users"
  ansible.builtin.set_fact:
    users:
      - "{{ my_essentials_user_username }}"
      - root

- name: "Role: my.essentials - install-vimrc.yml - clone the Vim configuration repository"
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: https://github.com/amix/vimrc.git
    dest: ~/.vim_runtime
    version: HEAD
    force: true
  with_items: "{{ users }}"
  tags:
    - skip_ansible_lint

- name: "Role: my.essentials - install-vimrc.yml - run the Vim installation script"
  become: true
  become_user: "{{ item }}"
  ansible.builtin.shell: sh ~/.vim_runtime/install_awesome_vimrc.sh
  args:
    executable: /bin/bash
  with_items: "{{ users }}"
  register: output
  changed_when: output.rc != 0
