# force installation of git

- name: my.essentials - install-dotfiles.yml - force install of git
  import_tasks: install-git.yml

# Install dotfiles for {{ my_essentials_user_username }}

- name: my.essentials - install-dotfiles.yml - recursively remove old dotfiles directory - {{ my_essentials_user_username }}
  file:
    path: /home/{{ item }}/dotfiles
    state: absent
  with_items: "{{ my_essentials_user_username }}"

- name: my.essentials - install-dotfiles.yml - clone the latest dotfiles repo to {{ my_essentials_user_username }}/dotfiles
  become: true
  become_user: "{{ my_essentials_user_username }}"
  git:
    repo: "{{ my_essentials_user_dotfiles_repo }}"
    dest: /home/{{ item }}/dotfiles
    recursive: yes # yes = incl. submodules
    force: yes
  with_items: "{{ my_essentials_user_username }}"

- name: my.essentials - install-dotfiles.yml - copy dotfiles-install.sh - {{ my_essentials_user_username }}
  become: true
  become_user: "{{ my_essentials_user_username }}"
  copy:
    src: files/scripts/dotfiles/dotfiles-install.sh
    dest: ~/dotfiles-install.sh
    mode: 0777

- name: my.essentials - install-dotfiles.yml - install dotfiles for {{ my_essentials_user_username }}
  become: true
  become_user: "{{ my_essentials_user_username }}"
  command: bash ~/dotfiles-install.sh

- name: my.essentials - install-dotfiles.yml - git config pull.rebase false - {{ my_essentials_user_username }}
  become: true
  become_user: "{{ my_essentials_user_username }}"
  command: chdir=~/dotfiles git config pull.rebase false

- name: my.essentials - install-dotfiles.yml - remove dotfiles-install.sh - {{ my_essentials_user_username }}
  become: true
  become_user: "{{ my_essentials_user_username }}"
  file:
    path: ~/dotfiles-install.sh
    state: absent

# Install dotfiles for root

- name: my.essentials - install-dotfiles.yml - recursively remove old dotfiles directory - root
  file:
    path: /root/dotfiles
    state: absent

- name: my.essentials - install-dotfiles.yml - clone the latest dotfiles repo to /root/dotfiles
  git:
    repo: "{{ my_essentials_user_dotfiles_repo }}"
    dest: /root/dotfiles
    recursive: yes # yes = incl. submodules
    force: yes

- name: my.essentials - install-dotfiles.yml - copy dotfiles-install.sh - root
  become: true
  become_user: root
  copy:
    src: files/scripts/dotfiles/dotfiles-install.sh
    dest: ~/dotfiles-install.sh
    mode: 0777

- name: my.essentials - install-dotfiles.yml - install dotfiles for root
  become: true
  become_user: root
  command: bash ~/dotfiles-install.sh

- name: my.essentials - install-dotfiles.yml - git config pull.rebase false - root
  become: true
  become_user: root
  command: chdir=~/dotfiles git config pull.rebase false

- name: my.essentials - install-dotfiles.yml - remove dotfiles-install.sh - root
  become: true
  become_user: root
  file:
    path: ~/dotfiles-install.sh
    state: absent