# https://github.com/chubin/cheat.sh#

- name: "Role: my.essentials - install-chtsh.yml - download cht.sh"
  ansible.builtin.get_url:
    url: https://cht.sh/:cht.sh
    dest: /usr/local/bin/cht.sh
    mode: "0755"

- name: "Role: my.essentials - install-chtsh.yml - change file ownership, group and permissions"
  ansible.builtin.file:
    path: /usr/local/bin/cht.sh
    owner: root
    group: root
    mode: "0755"

- name: "Role: my.essentials - install-chtsh.yml - create .config directory for '{{ my_essentials_user_username }}'"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.file:
    path: $HOME/.cht.sh
    state: directory
    mode: "0755"

- name: "Role: my.essentials - install-chtsh.yml - copy config.yaml to ~/.cht.sh - '{{ my_essentials_user_username }}'"
  become: true
  become_user: "{{ my_essentials_user_username }}"
  ansible.builtin.template:
    src: cht.sh.conf.j2
    dest: ~/.cht.sh/cht.sh.conf
    owner: "{{ my_essentials_user_username }}"
    group: "{{ my_essentials_user_username }}"
    mode: "0644"

- name: "Role: my.essentials - install-chtsh.yml - create .config directory for root"
  become: true
  become_user: root
  ansible.builtin.file:
    path: /root/.cht.sh
    state: directory
    mode: "0755"

- name: "Role: my.essentials - install-chtsh.yml - copy config.yaml to ~/.cht.sh - root"
  become: true
  become_user: root
  ansible.builtin.template:
    src: cht.sh.conf.j2
    dest: ~/.cht.sh/cht.sh.conf
    owner: root
    group: root
    mode: "0644"
