- name: "Role: my.essentials - install-git.yml - force install of git"
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
